#!/bin/bash
set -e

source $(dirname $0)/version

ARCH=${ARCH:?"ARCH not set"}
SUFFIX=""
[ "${ARCH}" != "amd64" ] && SUFFIX="_${ARCH}"

cd $(dirname $0)/../package

TAG=${TAG:-${VERSION}${SUFFIX}}
REPO=${REPO:-datawolf}

cp ../bin/code-examples .
docker build -t ${REPO}/code-examples:${TAG} .

echo Built ${REPO}/code-examples:${TAG}
